<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<testcase id="RHEL7-97447">
    <title>RHSM-TC : rhsm.cli.tests.BugzillaTests.testIPV4Facts</title>
    <description>verify fix for Bug 874147 - python-ethtool api changed causing facts to list ipv4 address as "unknown"</description>
    <test-steps>
        <test-step>
            <test-step-column id="step"/>
        </test-step>
    </test-steps>
    <custom-fields>
        <custom-field id="caseautomation" content="automated"></custom-field>
        <custom-field id="caseimportance" content="high"></custom-field>
        <custom-field id="caselevel" content="component"></custom-field>
        <custom-field id="caseposneg" content="positive"></custom-field>
        <custom-field id="tags" content="Tier3"></custom-field>
        <custom-field id="casecomponent" content="subscription-manager"></custom-field>
        <custom-field id="testtype" content="functional"></custom-field>
        <custom-field id="subtype1" content="reliability"></custom-field>
        <custom-field id="subtype2" content="-"></custom-field>
    </custom-fields>
</testcase>
